

...
1
Data
كل النصوص والقيم الموجودة داخل data()
2
Interpolation {{ }}
عرض النصوص مثل {{ portalName }}
3
Attribute Binding v-bind / :
ربط الصور مثل :src="logo"
4
Event Handling v-on / @
الزر @click="showServices"
5
Methods
الدالة showServices()
6
Two-Way Binding v-model
مربع البحث v-model="requestSearch"
7
Conditional Rendering v-if
رسالة النجاح ورسالة عدم وجود نتيجة
8
Visibility v-show
إظهار/إخفاء بطاقة الطلب
9
Computed Properties
showFirstRequest و requestStatusClass
10
Class Binding :class
تغيير شكل حالة الطلب
11
Style Binding :style

12
v-for
استخدمتا بعرض الخدمات 
13
components 
استخدمتا ب 
navbar + footer 
